package java.domain.models.enums;

public enum AreaConhecimento {
    LITERATURA, HISTORIA, GEOGRAFIA, CIENCIAS_NATURAIS, CIENCIAS_EXATAS,
    FILOSOFIA, SOCIOLOGIA, PSICOLOGIA, TECNOLOGIA, ENGENHARIA, MATEMATICA,
    FISICA, QUIMICA, BIOLOGIA, ARTES, MUSICA, EDUCACAO, DIREITO, ADMINISTRACAO,
    ECONOMIA, MEDICINA, RELIGIAO, ESPORTES, LINGUAS, OUTROS
}