package java.domain.models.enums;

public enum TipoCategoria {
    FICCAO, NAO_FICCAO, DIDATICO, PARADIDATICO, TECNICO, CIENTIFICO, BIOGRAFIA,
    POESIA, TEATRO, HQ, MANUAL, DICIONARIO, ENCICLOPEDIA, REVISTA, JORNAL, OUTROS
}